import json
import os
import webbrowser

from agents.search_agent import run_search_agent
from agents.extractor_agent import extract_profile
from agents.validator_agent import validate_profile

from rag.vector_store import (
    store_documents,
    clear_collection
)

from services.image_service import (
    download_profile_image
)

from services.html_service import (
    generate_html
)

from services.pdf_service import (
    generate_pdf
)


def generate_profile(name, context):

    try:

        print("\n" + "=" * 50)
        print("PROFILE GENERATION STARTED")
        print("=" * 50)

        # SEARCH

        print("\nSearching Documents...")

        docs = run_search_agent(
            name,
            context
        )

        print(
            f"Documents Found: {len(docs)}"
        )

        if not docs:

            return {
                "error":
                "No documents found."
            }

        # CLEAR CHROMADB

        print(
            "\nClearing Old ChromaDB..."
        )

        clear_collection()

        # STORE DOCUMENTS

        print(
            "Storing Documents In ChromaDB..."
        )

        store_documents(docs)

        # EXTRACT PROFILE

        print(
            "\nExtracting Profile..."
        )

        profile = extract_profile(
            name,
            context
        )

        # STRING → JSON

        if isinstance(profile, str):

            profile = profile.replace(
                "```json",
                ""
            )

            profile = profile.replace(
                "```",
                ""
            )

            profile = profile.strip()

            try:

                profile_json = json.loads(
                    profile
                )

            except Exception as e:

                print(
                    "JSON Parsing Error:",
                    str(e)
                )

                return {
                    "error":
                    "Invalid JSON Generated By Gemini",
                    "raw_output":
                    profile
                }

        else:

            profile_json = profile

        # VALIDATE PROFILE

        print(
            "\nValidating Profile..."
        )

        warnings = validate_profile(
            profile_json
        )

        profile_json[
            "validation_warnings"
        ] = warnings

        # DOWNLOAD IMAGE

        print(
            "\nDownloading Profile Image..."
        )

        image_path = download_profile_image(
            name
        )

        if image_path:

            abs_path = os.path.abspath(
                image_path
            )

            profile_json[
                "image_url"
            ] = (
                "file:///" +
                abs_path.replace(
                    "\\",
                    "/"
                )
            )

            print(
                f"Image Saved: {image_path}"
            )

            print(
                f"Image URL: {profile_json['image_url']}"
            )

        else:

            profile_json[
                "image_url"
            ] = ""

            print(
                "No Image Found"
            )

        # SAVE JSON

        os.makedirs(
            "output",
            exist_ok=True
        )

        json_file = (
            "output/profile.json"
        )

        with open(
            json_file,
            "w",
            encoding="utf-8"
        ) as f:

            json.dump(
                profile_json,
                f,
                indent=4,
                ensure_ascii=False
            )

        print(
            f"\nProfile Saved: {json_file}"
        )

        # GENERATE HTML

        print(
            "\nGenerating HTML Report..."
        )

        html_file = generate_html()

        print(
            f"HTML Generated: {html_file}"
        )

        # GENERATE PDF

        print(
            "\nGenerating PDF Report..."
        )

        pdf_file = generate_pdf()

        print(
            f"PDF Generated: {pdf_file}"
        )

        # OPEN HTML REPORT

        try:

            html_path = os.path.abspath(
                html_file
            )

            webbrowser.open(
                "file:///" +
                html_path.replace(
                    "\\",
                    "/"
                )
            )

            print(
                "\nOpening Report..."
            )

        except Exception as e:

            print(
                "Browser Error:",
                str(e)
            )

        print("\n" + "=" * 50)
        print("PROFILE GENERATION COMPLETED")
        print("=" * 50)

        return profile_json

    except Exception as e:

        print(
            "\nPROFILE AGENT ERROR:",
            str(e)
        )

        return {
            "error": str(e)
        }